ALTER TABLE Orders
DROP CONSTRAINT IF EXISTS fk_user,
ADD CONSTRAINT fk_user FOREIGN KEY (userid)
REFERENCES Users (ID) ON DELETE SET NULL;

ALTER TABLE Orders
DROP CONSTRAINT IF EXISTS fk_TravelAgency,
ADD CONSTRAINT fk_TravelAgency FOREIGN KEY (TravelAgencyid)
REFERENCES TravelAgencies (ID) ON DELETE SET NULL;