CREATE TABLE IF NOT EXISTS Passports (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Number VARCHAR(20) NOT NULL UNIQUE,
    DateOfIssue DATE NOT NULL,
    UserID INTEGER REFERENCES Users (ID)
);