CREATE TABLE IF NOT EXISTS Tours (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Title VARCHAR(50) NOT NULL,
    CategoryID INTEGER NOT NULL REFERENCES TourCategories (ID),
    TravelAgencyID INTEGER NOT NULL REFERENCES TravelAgencies (ID)
);