CREATE TABLE IF NOT EXISTS Tours (
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Title VARCHAR(50) NOT NULL,
    Telephone VARCHAR(20),
    INN VARCHAR(50) NOT NULL,
    TravelAgencyID INTEGER NOT NULL REFERENCES TravelAgencies (ID)
);