CREATE TABLE IF NOT EXISTS VisaCountries(
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    VisaID INTEGER NOT NULL REFERENCES VisaTypes (ID),
    CountryID INTEGER NOT NULL REFERENCES Countries (ID)
)