CREATE TABLE IF NOT EXISTS VisaCountries(
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    VisaID INTEGER NOT NULL REFERENCES VisaTypes (ID) ON DELETE CASCADE,
    CountryID INTEGER NOT NULL REFERENCES Countries (ID) ON DELETE CASCADE
)